### ISSUE TITLE
shadow-elevation-16dp white space vs gulp task

### ISSUE THREAD

**Issue by Zecat** [PolymerElements/paper-styles#83]
https://github.com/PolymerElements/paper-styles/blob/master/classes/shadow.html#L48-L49
```css
.shadow-elevation-16dp {
  box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14),
              0  6px 30px 5px rgba(0, 0, 0, 0.12),
              0  8px 10px -5px rgba(0, 0, 0, 0.4);
}
```
https://github.com/PolymerElements/paper-styles/blob/master/shadow.html#L59-L60
```css
--shadow-elevation-16dp: {
  box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14),
              0  6px 30px 5px rgba(0, 0, 0, 0.12),
              0  8px 10px -5px rgba(0, 0, 0, 0.4);
};
```

Using the default gulp task from polymer starterkit, it resolve to :

```css
.shadow-elevation-16dp {
  box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14),06px 30px 5px rgba(0, 0, 0, 0.12),08px 10px -5px rgba(0, 0, 0, 0.4);
}
```

It's silly but the white space used to align the lines for box-shadow properties are misinterpreted. I suppose it's an issue from gulp-cssmin, but could we remove these white space for now ?
